# Sets up the overall controller manager for MoveIt
trajectory_execution:
  allowed_execution_duration_scaling: 1.2
  allowed_goal_duration_margin: 0.05
  allowed_start_tolerance: 0.01
  # trajectory_duration_monitoring: true
  use_sim_time: true
  
moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_controller
    - rw1_controller
    - rw2_controller
    - rw3_controller
    - rw4_controller

  arm_controller: #Sets up the ROS2 action space
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - joint_1_s
      - joint_2_l
      - joint_3_u
      - joint_4_r
      - joint_5_b
      - joint_6_t

  rw1_controller: #Sets up the ROS2 action space
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - rw1_joint

  rw2_controller: #Sets up the ROS2 action space
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - rw2_joint

  rw3_controller: #Sets up the ROS2 action space
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - rw3_joint

  rw4_controller: #Sets up the ROS2 action space
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - rw4_joint