# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  joint_1_s:
    has_velocity_limits: true
    max_velocity: 1.570796326794897
    has_acceleration_limits: false
    max_acceleration: 0
  joint_2_l:
    has_velocity_limits: true
    max_velocity: 1.48352986419518
    has_acceleration_limits: false
    max_acceleration: 0
  joint_3_u:
    has_velocity_limits: true
    max_velocity: 1.48352986419518
    has_acceleration_limits: false
    max_acceleration: 0
  joint_4_r:
    has_velocity_limits: true
    max_velocity: 3.054326190990077
    has_acceleration_limits: false
    max_acceleration: 0
  joint_5_b:
    has_velocity_limits: true
    max_velocity: 2.617993877991494
    has_acceleration_limits: false
    max_acceleration: 0
  joint_6_t:
    has_velocity_limits: true
    max_velocity: 4.188790204786391
    has_acceleration_limits: false
    max_acceleration: 0
  # rw1_joint:
  #   min_position: -6.283185307179586
  #   max_position: 6.283185307179586
  # rw2_joint:
  #   min_position: -6.283185307179586
  #   max_position: 6.283185307179586
  # rw3_joint:
  #   min_position: -6.283185307179586
  #   max_position: 6.283185307179586
  # rw4_joint:
  #   min_position: -6.283185307179586
  #   max_position: 6.283185307179586